"""
Django settings for project project.
Generated by 'django-admin startproject' using Django 2.1.1.
For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys

from corsheaders.defaults import default_headers
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURE_SSL_REDIRECT = True
# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Force HTTPS in the final URIs
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'rest_framework',
    'togther',
    'django_select2',
    'corsheaders',
    'collabmates_api',
    'crispy_forms',
    'utility',
    'django_celery_beat',
    'cms',
    'django_prometheus',
    'django_elasticsearch_dsl',
    'django_elasticsearch_dsl_drf',
]


MIDDLEWARE = [
    # 'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'middleware.CustomPrometheusAfterMetrics.CustomPrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'utility.custom_middleware.AppendOrRemoveSlashMiddleware',
    'middleware.CustomAuthenticateUserID.CustomAuthenticateUserIDMiddleware',
    'middleware.api_logger.ApiLogger',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]


CRISPY_TEMPLATE_PACK = 'bootstrap4'

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# for encrypting and decryption for link
ENCRYPT_KEY = b'yo0TkK34DzXNAr9sTEnT-vajau2ntgd6oFvwZt0k3dQ='
# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.linkedin.LinkedinOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_FACEBOOK_KEY = os.getenv('SOCIAL_AUTH_FACEBOOK_KEY')
SOCIAL_AUTH_FACEBOOK_SECRET = os.getenv('SOCIAL_AUTH_FACEBOOK_SECRET')

SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {'fields': 'id,name,email', }

SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = os.getenv('SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY')        # Client ID
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = os.getenv('SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET')  # Client Secret
# SOCIAL_AUTH_LINKEDIN_OAUTH2_SCOPE = ['r_basicprofile','r_emailaddress','rw_company_admin','w_share']


SOCIAL_AUTH_LINKEDIN_OAUTH2_SCOPE = ['r_emailaddress']
# SOCIAL_AUTH_LINKEDIN_OAUTH2_WHITELISTED_DOMAINS=['*']

SOCIAL_AUTH_LOGIN_URL = ""
SOCIAL_AUTH_LOGIN_REDIRECT_URL = "dashboard"
SOCIAL_AUTH_LOGIN_ERROR_URL = "error"

SOCIAL_AUTH_LINKEDIN_OAUTH2_FIELD_SELECTORS = ['emailAddress', 'formatted-name', 'public-profile-url', 'picture-url']

SOCIAL_AUTH_LINKEDIN_OAUTH2_EXTRA_DATA = [
    ('id', 'id'),
    ('formattedName', 'name'),
    ('emailAddress', 'email_address'),
    ('pictureUrl', 'picture_url'),
    ('publicProfileUrl', 'profile_url')]

SOCIAL_AUTH_PIPELINE = (
    # Get the information we can about the user and return it in a simple
    # format to create the user instance later. On some cases the details are
    # already part of the auth response from the provider, but sometimes this
    # could hit a provider API.
    'social_core.pipeline.social_auth.social_details',

    # Get the social uid from whichever service we're authing thru. The uid is
    # the unique identifier of the given user in the provider.
    'social_core.pipeline.social_auth.social_uid',

    # Verifies that the current auth process is valid within the current
    # project, this is where emails and domains whitelists are applied (if
    # defined).
    'social_core.pipeline.social_auth.auth_allowed',

    # Checks if the current social-account is already associated in the site.
    'social_core.pipeline.social_auth.social_user',

    # Make up a username for this person, appends a random string at the end if
    # there's any collision.
    'social_core.pipeline.user.get_username',

    # Send a validation email to the user to verify its email address.
    # Disabled by default.
    # 'social_core.pipeline.mail.mail_validation',

    # Associates the current social details with another user account with
    # a similar email address. Disabled by default.
    'social_core.pipeline.social_auth.associate_by_email',

    # Create a user account if we haven't found one yet.
    'social_core.pipeline.user.create_user',

    # Create the record that associates the social account with the user.
    'social_core.pipeline.social_auth.associate_user',

    # Populate the extra_data field in the social record with the values
    # specified by settings (and the default ones like access_token, etc).
    'social_core.pipeline.social_auth.load_extra_data',

    # Update the user record with any changed info from the auth service.
    'social_core.pipeline.user.user_details',

    # create userinfo after as soon as user creation is done
    'utility.userinfo_pipeline.update_userinfo',

)

GROWTH_TEAM_MAILS = ['growth@likeminds.community']
BACKEND_TEAM_MAILS = ['backend@likeminds.community']

SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_BACKEND = "sgbackend.SendGridBackend"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-member-id',
    'x-platform-code',
    'x-version-code',
    'x-sdk-source',
    'x-username',
    'x-password',
    'x-device-id',
    'x-api-key',
    'x-accept-version',
]

FCM_DJANGO_SETTINGS = {
    "FCM_SERVER_KEY":  os.getenv('PROD_FCM_SERVER_KEY'),
    "ONE_DEVICE_PER_USER": True,
    "DELETE_INACTIVE_DEVICES": False
}

GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')


EMAIL_GHUPSHAP_KEY = os.getenv('GUPSHUP_EMAIL_TEMPLATE_KEY')
GUPSHUP_ID = os.getenv('GUPSHUP_USER_ID_FOR_INDIA')
GUPSHUP_PASS = os.getenv('GUPSHUP_PASSWORD_ID_FOR_INDIA')

MSG91_AUTH_KEY = '348626A9QYSV99f2sb5fc9defeP1'

INTERNATIONAL_GHUPSHAP = {
    'user_id': '2000193536',
    'password': 'GIYMA8Kcf',
    'msg': """%25code%25%20is%20your%20OTP%20for%20LikeMinds.%20For%20security%20reasons%2C%20do%20not%20share%20this%20OTP%20with%20anyone.%20cW6ZEtFKpHc"""
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'external_services.logging.json_formatter.JsonFormatter',
        }
    },
    'handlers': {
        'file_handler': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'maxBytes': 1024 * 10 * 10,  # 10 MB
            'backupCount': 5,
            'filename': 'utility/logs/custom.log',
            'formatter': 'json',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'utility/logs/collabmates.log',
            'maxBytes': 1024 * 10 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'json',
        },
        'stream_info_handler': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'json'
        },
        'stream_error_handler': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
            'stream': sys.stderr,
            'formatter': 'json'
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
            'formatter': 'json'
        },
    },
    'loggers': {
        'file_logger': {
            'handlers': ['file_handler'],
            'level': 'INFO',
            'propagate': False,
        },
        'stream_info_logger': {
            'handlers': ['stream_info_handler'],
            'level': 'INFO',
            'propagate': False,
        },
        'stream_error_logger': {
            'handlers': ['stream_error_handler'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'stream_info_handler', 'stream_error_handler', 'mail_admins'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
    },
}


BRANCH_KEY = 'key_live_lkM4vHEWt2Mhx2hJxxtU8deburgYWup4'

MIXPANEL_TOKEN = os.getenv('MIXPANEL_TOKEN')

ELASTICSEARCH_DSL = {
    'default': {
        'hosts': os.getenv('ELASTIC_SEARCH_HOST'),
        'timeout': 60,
    },
}

# Name of the Elasticsearch index
ELASTICSEARCH_INDEX_NAMES = {
    'collabmates_api.search.chatroom_index': 'chatroom',
    'collabmates_api.search.conversation_index': 'conversation',
    'collabmates_api.search.member_directory_index': 'member_directory',
}

SUBSCRIPTION_SERVER_URL = os.getenv('SUBSCRIPTION_SERVER_URL')

# whatsapp api key to send broadcast messages
WA_API_KEY = os.getenv('WA_API_KEY')

CONFIG_FLAGS = {
    'SEGMENT': os.getenv('SEGMENT'),
    'MICRO_POLLS': os.getenv('MICRO_POLLS'),
    'GIF': os.getenv('GIF'),
    'AUDIO': os.getenv('AUDIO'),
    'VOICE_NOTES': os.getenv('VOICE_NOTES')
}


FORCE_UPDATE = {
    'android': os.getenv('ANDROID_FORCE_UPDATE'),
    'ios': os.getenv('IOS_FORCE_UPDATE')
}

SEGMENT_KEY = os.getenv('SEGMENT_KEY')

WEBFLOW_KEYS = {
    'collection_id': os.getenv('WEBFLOW_COLLECTION_ID'),
    'api_key': os.getenv('WEBFLOW_API_KEY'),
    'web_url': os.getenv('WEBFLOW_URL')
}

FCM_TIMEOUT_SECONDS = 120

MAX_INDEX_LENGTH_ELASTICSEARCH = 32765

# Indexing only settings
ELASTICSEARCH_DSL_QUERYSET_PAGINATION = 10000

# ASYNCHRONOUS QUEUE SETTINGS
ELASTIC_SEARCH_QUEUE_NAME = os.getenv('ELASTIC_SEARCH_QUEUE_NAME')

SERVER_TYPE = os.getenv('SERVER_TYPE', 'API-SERVER')

if SERVER_TYPE != "MIGRATION":
    # Elastic search signal processor
    ELASTICSEARCH_DSL_SIGNAL_PROCESSOR = "collabmates_api.search.custom_signal_processor.CelerySignalProcessor"

OG_TAGS_URL_REQUEST_TIMEOUT_IN_SECONDS = os.getenv('OG_TAGS_URL_REQUEST_TIMEOUT_IN_SECONDS')

MIGRATE_TO_S3_LAMBDA_URL = os.getenv("MIGRATE_TO_S3_LAMBDA_URL")

CLOUDWATCH_LOG_GROUP = os.getenv('CLOUDWATCH_LOG_GROUP')
CLOUDWATCH_KUBERNETES_CONTAINER_NAME = os.getenv('CLOUDWATCH_KUBERNETES_CONTAINER_NAME')
CLOUDWATCH_AWS_ACCESS_KEY_ID = os.getenv('CLOUDWATCH_AWS_ACCESS_KEY_ID')
CLOUDWATCH_AWS_SECRET_ACCESS_KEY = os.getenv('CLOUDWATCH_AWS_SECRET_ACCESS_KEY')
AWS_REGION = os.getenv('AWS_REGION')

APP_VERSION = '2.68.1'
