apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "caravan-celery-es"
  namespace: "app-deploy"
  labels:
    app: "caravan-celery-es"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "caravan-celery-es"
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: "caravan-celery-es"
    spec:
      containers:
      - name: "likeminds-caravan-celery-es-1"
        image: "asia.gcr.io/likeminds-nonprod-prj-24e1/github.com/nateshr/togther/caravan-celery-es:93ce10d"
        resources:
          requests:
            memory: "1000Mi"
            cpu: "500m"
          limits:
            memory: "1500Mi"
            cpu: "1000m"
        env:
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: caravan-celery-secret
              key: CELERY_BROKER_URL
  
---

apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "caravan-celery-es"
  namespace: "app-deploy"
  labels:
    app: "caravan-celery-es"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "caravan-celery-es"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 75
