apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "caravan-celery-es"
  namespace: "app-deploy"
  labels:
    app: "caravan-celery-es"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: "caravan-celery-es"
  template:
    metadata:
      labels:
        app: "caravan-celery-es"
    spec:
      containers:
      - name: "likeminds-caravan-celery-es-1"
        image: "asia.gcr.io/likeminds-prod-prj-5464/togther/caravan-celery-es-prod:5661bfc"
        env:
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: caravan-celery-secret
              key: CELERY_BROKER_URL          
