# syntax=docker/dockerfile:1

FROM ubuntu:20.04

RUN apt-get update && apt-get install -y software-properties-common gcc && \
    add-apt-repository -y ppa:deadsnakes/ppa

RUN apt-get update && apt-get install -y python3.9 python3.9-distutils python3.9-pip python3.9-apt python3.9-venv libpq-dev python3.9-dev

WORKDIR /usr/src/app

COPY ./project/requirements.txt requirements.txt

ENV VIRTUAL_ENV=/opt/venv
RUN python3.9 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
ENV SERVER_TYPE="API-SERVER"

RUN pip3 install -r requirements.txt

ADD . $WORKDIR

RUN mkdir /usr/src/app/project/utility/logs && \
    touch /usr/src/app/project/utility/logs/collabmates.log && \
    touch /usr/src/app/project/utility/logs/custom.log

RUN chmod +x ./docker-entrypoint/entry-caravan-prod.sh

CMD [ "/bin/bash", "./docker-entrypoint/entry-caravan-prod.sh" ]
