from django.contrib import admin
from togther.models import *
# Register your models here.
#admin.site.register(User)
admin.site.register(Userinfo)
# admin.site.register(Admins)
admin.site.register(Members)
admin.site.register(Community)
#admin.site.register(Requests)
#admin.site.register(Community_tags)
#admin.site.register(Form_response)
#admin.site.register(Form_data)
#admin.site.register(Experience)
admin.site.register(Collabcard)
#admin.site.register(Comments)
#admin.site.register(Cardaction)
admin.site.register(card_answers)
admin.site.register(Card_Attachment)
admin.site.register(temp_admin)
#admin.site.register(userinfo_tags)
#admin.site.register(follow_collabcard)
#admin.site.register(collabcard_seen)
admin.site.register(Tags_lpig)
admin.site.register(Community_Legacy)
admin.site.register(Community_Profession)
admin.site.register(Community_Interest)
admin.site.register(Community_Geography)
admin.site.register(User_Legacy)
admin.site.register(User_Profession)
admin.site.register(User_Interest)
admin.site.register(User_Geography)
admin.site.register(Location_Info)
admin.site.register(Member_Engage)


admin.site.register(communityFieldTypes)
admin.site.register(communityFieldSubTypes)
admin.site.register(communityField)

