from django.urls import path, include
from . import views

urlpatterns = [
    path('login/', views.home, name="home"),
    path('signup/', views.signup, name="signup"),
    path('privacy/', views.privacy, name="privacy"),
    path('terms/', views.terms, name="terms"),
    path('communities/', views.dashboard, name="dashboard"),
    path('dashboard/<slug:data>', views.dashboard, name="dashboard1"),
    path('dashboard/recieved_requests', views.recieved_requests, name="recieved_requests"),
    path('community/<int:community_id>&cta=join', views.join_community, name="join_community"),
    path('requests', views.check_requests,name="check_requests"),
    path('requests/<int:community_id>/user_response/<int:user_id>', views.user_response,name="user_response"),
    path('community/<int:community_id>', views.community, name="comunity"),
    path('community/<int:community_id>/members_list', views.members_list, name="members_list"),
    path('create_community/', views.creategroup, name="create"),
    path('profile/<int:user_id>', views.profile, name="profile"),
    path('profile/<int:user_id>/mycommunities', views.my_communities, name="my_communities"),
    path('profile/<int:user_id>/communities_as_admin', views.communities_as_admin, name="communities_as_admin"),
    path('request_response', views.request_response, name="request_response"),
    path('profile/<int:user_id>/edit',views.edit_profile, name = "edit_profile"),
    path('logout',views.logout_view, name = "logout_view"),
    path('creategroup/<int:community_id>/form_data',views.form_data,name='form_data'),
    path('thankyou', views.thankyou, name="thankyou"),
    path('collabcard/<int:card_id>', views.collabcard, name="card"),
    path('view_answers/<int:card_id>',views.view_answers,name = 'view_answers'),
    path('accept_admin/<int:community_id>',views.accept_admin,name='accept_admin'),
    path('', views.index, name='index'),
    path('create_message', views.create_message, name='create_message'),
    path('pending_list/<int:community_id>', views.pending_list, name='pending_list'),
    path('questions_responses', views.questions_responses, name='questions_responses'),
    path('onboarding', views.onboarding, name='onboarding'),
    path('onboarding_profession', views.onboarding_profession, name='onboarding_profession'),
    path('onboarding_interest', views.onboarding_interest, name='onboarding_interest'),
    path('access_page', views.access_page, name='access_page'),
    path('alpha_page', views.alpha_page, name='alpha_page'),
    path('refer_members/<int:community_id>', views.refer_members, name='refer_members'),

]
