# Generated by Django 3.0.2 on 2022-03-08 10:26

from django.db import migrations, models
import django.db.models.deletion
import utility.states
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('togther', '0002_auto_20220225_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('icon_url', models.TextField()),
                ('banner_url', models.TextField(blank=True, null=True)),
                ('view_type', models.IntegerField(choices=[1, 2], default=1, help_text='1 - grid view, 2 - list view')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('level', models.IntegerField(blank=True, help_text='stores distance from root folder | root folder - 0', null=True)),
                ('created_at', models.BigIntegerField(default=0)),
                ('updated_at', models.BigIntegerField(default=0)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='togther.Community')),
                ('parent_category_id', models.ForeignKey(blank=True, help_text='Stores pk of parent category id', null=True, on_delete=django.db.models.deletion.PROTECT, to='collabmates_api.ResourceCategory')),
            ],
            options={
                'verbose_name': 'Resouce Category',
                'verbose_name_plural': 'Resouce Categorys',
                'db_table': 'togther_resource_category',
            },
        ),
        migrations.CreateModel(
            name='ResourceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('day_of_weekly_email', models.IntegerField(choices=[0, 1, 2, 3, 4, 5, 6])),
                ('time_of_weekly_email', models.IntegerField(choices=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])),
                ('created_at', models.BigIntegerField(default=0)),
                ('updated_at', models.BigIntegerField(default=0)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='togther.Community')),
            ],
            options={
                'verbose_name': 'Resouce Setting',
                'verbose_name_plural': 'Resouce Settings',
                'db_table': 'togther_resource_settings',
            },
        ),
        migrations.CreateModel(
            name='ResourceCategoryPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('access_type', models.IntegerField(choices=[1, 2, 3], help_text='1 - access, 2 - restricted access, 3 - no access')),
                ('created_at', models.BigIntegerField(default=0)),
                ('updated_at', models.BigIntegerField(default=0)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collabmates_api.ResourceCategory')),
                ('cohort_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='togther.Cohort')),
            ],
            options={
                'verbose_name': 'Resouce Category Permission',
                'verbose_name_plural': 'Resouce Category Permissions',
                'db_table': 'togther_resource_category_permission',
            },
        ),
        migrations.CreateModel(
            name='CommunityWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('webhook_type', models.IntegerField(choices=[(1, utility.states.WebhookTypes['COMMUNITY_JOIN'])])),
                ('created_at', models.BigIntegerField(default=0)),
                ('updated_at', models.BigIntegerField(default=0)),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='togther.Community')),
            ],
        ),
    ]
