# Generated by Django 3.0.2 on 2020-09-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewCommunities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.IntegerField(default=0)),
                ('created_at', models.BigIntegerField(default=0)),
                ('updated_at', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PerDayRecordOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_communities', models.IntegerField(default=0)),
                ('cumulative_communities', models.IntegerField(default=0)),
                ('new_chatrooms', models.IntegerField(default=0)),
                ('new_cm_chatrooms', models.IntegerField(default=0)),
                ('new_intro_rooms', models.IntegerField(default=0)),
                ('new_messages', models.IntegerField(default=0)),
                ('new_intro_room_messages', models.IntegerField(default=0)),
                ('new_intro_poll_messages', models.IntegerField(default=0)),
                ('new_intro_event_messages', models.IntegerField(default=0)),
                ('new_messages_by_cm', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('new_users_cumulative', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('members_added', models.IntegerField(default=0)),
                ('created_at', models.BigIntegerField(default=0)),
                ('updated_at', models.BigIntegerField(default=0)),
            ],
        ),
    ]
