# Generated by Django 2.1.1 on 2018-09-15 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('members_count', models.IntegerField(default=0)),
                ('active_since', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Community')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Community')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('fb_token', models.TextField()),
                ('linkdin_token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('gender', models.IntegerField()),
                ('image_url', models.CharField(max_length=200)),
                ('interests', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.User')),
            ],
        ),
        migrations.AddField(
            model_name='requests',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.User'),
        ),
        migrations.AddField(
            model_name='members',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.User'),
        ),
        migrations.AddField(
            model_name='category',
            name='community_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Community'),
        ),
        migrations.AddField(
            model_name='admins',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.User'),
        ),
        migrations.AddField(
            model_name='admins',
            name='community_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Community'),
        ),
    ]
