# Generated by Django 2.1.1 on 2019-04-15 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='card_answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='card_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='media/collabcardImages')),
            ],
        ),
        migrations.CreateModel(
            name='Cardaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('pdf', 'PDF')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Collabcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('likes_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('answers_count', models.IntegerField(default=0)),
                ('answer_text', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Collabcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('purpose', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=200)),
                ('image_url', models.ImageField(default='https://upload.wikimedia.org/wikipedia/en/0/09/Community_title.jpg', upload_to='media/')),
                ('members_count', models.IntegerField(default=0)),
                ('active_since', models.DateField(auto_now_add=True)),
                ('whatsapp_group_link', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituion', models.CharField(max_length=200, null=True)),
                ('degree', models.CharField(max_length=200, null=True)),
                ('field_of_study', models.CharField(max_length=200, null=True)),
                ('from_year', models.CharField(max_length=4, null=True)),
                ('to_year', models.CharField(max_length=4, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('company', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('from_year', models.CharField(max_length=4, null=True)),
                ('to_year', models.CharField(max_length=4, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=400)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('pdf', 'PDF')], default='text', max_length=20)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Community')),
            ],
        ),
        migrations.CreateModel(
            name='Form_response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('user', models.IntegerField()),
                ('community', models.IntegerField()),
                ('response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Community')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Community')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='temp_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Community')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=200, null=True)),
                ('gender', models.IntegerField(null=True)),
                ('image_url', models.CharField(max_length=500, null=True)),
                ('interests', models.CharField(max_length=400, null=True)),
                ('about', models.CharField(max_length=400, null=True)),
                ('fb_link', models.CharField(max_length=400, null=True)),
                ('linkedin_link', models.CharField(max_length=400, null=True)),
                ('headline', models.CharField(max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='requests',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Userinfo'),
        ),
        migrations.AddField(
            model_name='experience',
            name='user_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='togther.Userinfo'),
        ),
        migrations.AddField(
            model_name='education',
            name='user_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='togther.Userinfo'),
        ),
        migrations.AddField(
            model_name='collabcard',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Community'),
        ),
        migrations.AddField(
            model_name='collabcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='community_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Community'),
        ),
        migrations.AddField(
            model_name='cardaction',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Collabcard'),
        ),
        migrations.AddField(
            model_name='cardaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card_images',
            name='collabcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Collabcard'),
        ),
        migrations.AddField(
            model_name='card_answers',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Collabcard'),
        ),
        migrations.AddField(
            model_name='card_answers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admins',
            name='community_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Community'),
        ),
    ]
