# Generated by Django 2.1.1 on 2018-10-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=400)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Community')),
            ],
        ),
        migrations.CreateModel(
            name='Form_response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Form_data')),
            ],
        ),
    ]
