# Generated by Django 2.1.1 on 2019-04-22 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collabcard',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='collabcard',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='community',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
