# Generated by Django 3.0.2 on 2020-09-10 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('togther', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='collabcardpolls',
        #     name='user',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='conversationengage',
        #     name='community',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='togther.Community'),
        # ),
        migrations.AddField(
            model_name='deletedchatrooms',
            name='deleted_by_creator',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='deletedchatrooms',
            name='deleted_by_promoter',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='deletedchatrooms',
            name='deleted_by_text',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='deletedchatrooms',
            name='deleted_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deletedchatrooms',
            name='reason',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='deletedchatrooms',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='togther.Report_Tags'),
        ),
        migrations.AlterField(
            model_name='collabcard',
            name='multiple_select_state',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='CollabcardStateBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(null=True)),
                ('created_at', models.BigIntegerField(default=0, null=True)),
                ('updated_at', models.BigIntegerField(default=0, null=True)),
                ('seen_status', models.BooleanField(default=False)),
                ('mute_status', models.BooleanField(default=False)),
                ('follow_status', models.BooleanField(default=False)),
                ('is_guest', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.deletedChatrooms')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Community')),
                ('remove', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='togther.removedMembers')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrer_backup', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
