# Generated by Django 2.1.1 on 2019-04-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardaction',
            name='date',
            field=models.DateField(auto_now_add=True, default='2018-12-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collabcard',
            name='date',
            field=models.DateField(auto_now_add=True, default='2018-12-04'),
            preserve_default=False,
        ),
    ]
