# Generated by Django 2.1.1 on 2018-10-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0002_form_data_form_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='profile_completed',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='college',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='contact_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='experience',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='interests',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
