# Generated by Django 3.0.2 on 2020-09-10 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('togther', '0002_auto_20200910_0949'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='collabcardpolls',
        #     name='user',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        migrations.AddField(
            model_name='collabcardstate',
            name='expiry_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='collabcardstate',
            name='external_seen',
            field=models.BooleanField(default=False),
        ),
        # migrations.AddField(
        #     model_name='conversationengage',
        #     name='community',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='togther.Community'),
        # ),
        # migrations.AddField(
        #     model_name='conversationengage',
        #     name='expiry_time',
        #     field=models.BigIntegerField(null=True),
        # ),
    ]
