# Generated by Django 2.1.1 on 2019-04-30 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('togther', '0002_auto_20190422_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='collabcard_seen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='cardaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='collabcard',
            name='date',
        ),
        migrations.AddField(
            model_name='collabcard_seen',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Collabcard'),
        ),
        migrations.AddField(
            model_name='collabcard_seen',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Community'),
        ),
        migrations.AddField(
            model_name='collabcard_seen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
