# Generated by Django 3.0.2 on 2020-09-10 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('togther', '0003_auto_20200910_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_answers',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card_answers',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card_answers',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replied_conversation', to='togther.card_answers'),
        )
        # migrations.AddField(
        #     model_name='collabcardpolls',
        #     name='user',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='conversationengage',
        #     name='community',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='togther.Community'),
        # ),
    ]
