# Generated by Django 2.1 on 2019-06-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0003_auto_20190430_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabcard',
            name='date_epoch',
            field=models.BigIntegerField(default=-9223372036854775808),
        ),
    ]
