# Generated by Django 2.1.1 on 2018-10-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0003_auto_20181029_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image_url',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
