# Generated by Django 2.1.1 on 2018-10-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0004_auto_20181029_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_data',
            name='whatsapp_group_link',
            field=models.CharField(default='xyz.com', max_length=400),
            preserve_default=False,
        ),
    ]
