# Generated by Django 2.1 on 2019-06-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0004_collabcard_date_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='image_file',
            field=models.ImageField(null=True, upload_to='media/profile_pics/'),
        ),
    ]
