# Generated by Django 2.1 on 2019-06-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0005_userinfo_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='fcm_token',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
