# Generated by Django 3.0.2 on 2020-09-16 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('togther', '0005_auto_20200914_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_answers',
            name='internal_link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card_answers',
            name='preview_chatroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversation_preview_chatroom', to='togther.card_answers'),
        ),
        migrations.AddField(
            model_name='card_answers',
            name='preview_community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_preview_community', to='togther.Community'),
        ),
        migrations.AddField(
            model_name='card_answers',
            name='preview_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='collabcard',
            name='internal_link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='collabcard',
            name='preview_chatroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chatroom_preview_chatroom', to='togther.Collabcard'),
        ),
        migrations.AddField(
            model_name='collabcard',
            name='preview_community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_preview_community', to='togther.Community'),
        ),
        migrations.AddField(
            model_name='collabcard',
            name='preview_type',
            field=models.TextField(null=True),
        ),
        # migrations.AddField(
        #     model_name='collabcardpolls',
        #     name='user',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='conversationengage',
        #     name='community',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='togther.Community'),
        # ),
        # migrations.AddField(
        #     model_name='conversationengage',
        #     name='expiry_time',
        #     field=models.BigIntegerField(null=True),
        # ),
    ]
