# Generated by Django 2.1.1 on 2018-10-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0005_form_data_whatsapp_group_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_data',
            name='whatsapp_group_link',
        ),
        migrations.AddField(
            model_name='community',
            name='whatsapp_group_link',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
