# Generated by Django 2.1 on 2019-06-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0006_userinfo_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='state',
            field=models.IntegerField(null=True),
        ),
    ]
