# Generated by Django 2.1.1 on 2018-11-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0006_auto_20181030_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='about',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='experience',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image_url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='interests',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
