# Generated by Django 3.0.2 on 2020-09-16 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('togther', '0006_auto_20200916_1148'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='collabcardpolls',
        #     name='user',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='conversationengage',
        #     name='community',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='togther.Community'),
        # ),
        # migrations.AddField(
        #     model_name='conversationengage',
        #     name='expiry_time',
        #     field=models.BigIntegerField(null=True),
        # ),
        migrations.AlterField(
            model_name='card_answers',
            name='preview_chatroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversation_preview_chatroom', to='togther.Collabcard'),
        ),
    ]
