# Generated by Django 3.0.2 on 2020-09-16 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('togther', '0007_auto_20200916_1538'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='collabcardpolls',
        #     name='user',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        migrations.AddField(
            model_name='collabcardstate',
            name='is_tagged',
            field=models.BooleanField(default=False),
        ),
        # migrations.AddField(
        #     model_name='conversationengage',
        #     name='community',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='togther.Community'),
        # ),
        migrations.AddField(
            model_name='conversationengage',
            name='second_last_conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_last_conversation', to='togther.card_answers'),
        ),
        migrations.CreateModel(
            name='inActiveChatroomsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactive_count', models.IntegerField(default=0)),
                ('created_at', models.BigIntegerField(null=True)),
                ('updated_at', models.BigIntegerField(null=True)),
                ('last_inactive_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='togther.Collabcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
