# Generated by Django 2.1 on 2019-06-17 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0007_members_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_admin',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='togther.Members'),
            preserve_default=False,
        ),
    ]
