# Generated by Django 2.1.1 on 2018-11-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0007_auto_20181101_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='fb_link',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='linkedin_link',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
