# Generated by Django 3.0.2 on 2020-09-17 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('togther', '0008_auto_20200916_1709'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='collabcardpolls',
        #     name='user',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='conversationengage',
        #     name='community',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='togther.Community'),
        # ),
        migrations.AddField(
            model_name='member_engage',
            name='new_chatroom_users',
            field=models.TextField(null=True),
        ),
    ]
