# Generated by Django 2.1 on 2019-06-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0008_temp_admin_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabcard',
            name='answer_text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
