# Generated by Django 2.1.1 on 2018-11-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0008_auto_20181104_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image_url',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
