# Generated by Django 3.0.2 on 2020-09-24 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('togther', '0009_auto_20200917_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('sub_title', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='memberRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('sub_title', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inactivechatroomscount',
            name='last_inactive_card',
        ),
        # migrations.AddField(
        #     model_name='collabcardpolls',
        #     name='user',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='conversationengage',
        #     name='community',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='togther.Community'),
        # ),
        migrations.AddField(
            model_name='members',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='members',
            name='custom_title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='members',
            name='joined_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='members',
            name='parent_cm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_cm_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='members',
            name='parent_cm_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='collabcardstate',
            name='external_seen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deletedchatrooms',
            name='multiple_select_state',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='draftchatroom',
            name='multiple_select_state',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='userMemberRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Community')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.memberRights')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userAdminRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Community')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.adminRights')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
