# Generated by Django 2.1.1 on 2018-11-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0009_auto_20181104_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image_url',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
