# Generated by Django 2.1.1 on 2018-11-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0010_auto_20181104_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image_url',
            field=models.ImageField(default='http://localhost:8000/media/media/40af0d468633a4ee2f2344e6021f056b_2ouRHpe.jpg', upload_to='media/'),
            preserve_default=False,
        ),
    ]
