# Generated by Django 2.1 on 2019-06-18 13:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('togther', '0010_collabcard_follow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='collabcard_follow',
            new_name='follow_collabcard',
        ),
    ]
