# Generated by Django 2.1 on 2019-06-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0011_auto_20190618_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='updated_at',
            field=models.BigIntegerField(default=-9223372036854775808),
        ),
    ]
