# Generated by Django 2.1 on 2019-06-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0012_community_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='created_at',
            field=models.BigIntegerField(default=-9223372036854775808),
        ),
    ]
