# Generated by Django 2.1.1 on 2018-11-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0012_auto_20181104_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(null=True),
        ),
    ]
