# Generated by Django 2.1 on 2019-06-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0013_community_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_answers',
            name='date_epoch',
            field=models.BigIntegerField(default=-9223372036854775808),
        ),
    ]
