# Generated by Django 2.1.1 on 2018-11-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0013_auto_20181104_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
