# Generated by Django 2.1.1 on 2018-11-06 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0014_auto_20181104_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='education',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='experience',
        ),
        migrations.AddField(
            model_name='education',
            name='user_id',
            field=models.ForeignKey(default='6', on_delete=django.db.models.deletion.CASCADE, to='togther.Userinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='user_id',
            field=models.ForeignKey(default='6', on_delete=django.db.models.deletion.CASCADE, to='togther.Userinfo'),
            preserve_default=False,
        ),
    ]
