# Generated by Django 2.1 on 2019-06-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0014_card_answers_date_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='login_json',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='login_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
