# Generated by Django 2.1 on 2019-06-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0015_auto_20190625_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_admin',
            name='member_id',
            field=models.IntegerField(default=0),
        ),
    ]
