# Generated by Django 2.1.1 on 2018-11-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0015_auto_20181106_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_data',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('text_area', 'Text_area'), ('pdf', 'PDF')], default='text', max_length=20),
        ),
    ]
