# Generated by Django 2.1.1 on 2018-11-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0016_form_data_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='user_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='togther.Userinfo'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='user_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='togther.Userinfo'),
        ),
    ]
