# Generated by Django 2.1.1 on 2018-12-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0017_auto_20181106_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='about',
            field=models.CharField(max_length=300),
        ),
    ]
