# Generated by Django 2.1.1 on 2018-12-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0018_auto_20181204_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='purpose',
            field=models.CharField(default=' Nothing', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='about',
            field=models.TextField(),
        ),
    ]
