# Generated by Django 2.1.1 on 2018-12-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0019_auto_20181204_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_data',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('pdf', 'PDF')], default='text', max_length=20),
        ),
    ]
