# Generated by Django 2.1.1 on 2018-12-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0020_auto_20181204_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_response',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
