# Generated by Django 2.1.1 on 2018-12-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0021_form_response_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_response',
            name='data_id',
        ),
        migrations.AddField(
            model_name='form_response',
            name='data',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
