# Generated by Django 2.1.1 on 2018-12-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0022_auto_20181205_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_response',
            name='community',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
