# Generated by Django 2.1.1 on 2018-12-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0023_form_response_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='community_id',
            field=models.CharField(max_length=300),
        ),
    ]
