# Generated by Django 2.1.1 on 2018-12-05 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0024_auto_20181205_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='user_info',
            field=models.ForeignKey(default='27', on_delete=django.db.models.deletion.CASCADE, to='togther.Userinfo'),
            preserve_default=False,
        ),
    ]
