# Generated by Django 2.1.1 on 2018-12-06 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0025_requests_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='community_id',
        ),
        migrations.AddField(
            model_name='requests',
            name='community',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='togther.Community'),
            preserve_default=False,
        ),
    ]
