# Generated by Django 2.1.1 on 2018-12-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0026_auto_20181206_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='from_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='to_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='from_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='to_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
