# Generated by Django 2.1.1 on 2018-12-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0027_auto_20181207_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='apoorvkhare007@gmail.com', max_length=200),
            preserve_default=False,
        ),
    ]
