# Generated by Django 2.1.1 on 2019-03-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0029_auto_20190129_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabcard',
            name='title',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
