# Generated by Django 2.1.1 on 2019-03-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0031_card_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabcard',
            name='answers_count',
            field=models.IntegerField(default=0),
        ),
    ]
