# Generated by Django 2.1.1 on 2019-03-26 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0032_collabcard_answers_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_number', models.IntegerField(default=0, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Community')),
            ],
        ),
    ]
