# Generated by Django 2.1.1 on 2019-03-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0033_temp_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_admin',
            name='contact_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
