# Generated by Django 2.1.1 on 2019-03-27 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0034_auto_20190326_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='card_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='media/')),
                ('collabcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togther.Collabcard')),
            ],
        ),
    ]
