# Generated by Django 2.1 on 2019-03-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0035_card_images'),
        ('togther', '0033_card_images_temp_admin'),
    ]

    operations = [
    ]
