# Generated by Django 2.1.1 on 2019-04-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0035_card_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_images',
            name='image_url',
            field=models.ImageField(upload_to='media/collabcardImages'),
        ),
        migrations.AlterField(
            model_name='community',
            name='image_url',
            field=models.ImageField(default='https://upload.wikimedia.org/wikipedia/en/0/09/Community_title.jpg', upload_to='media/'),
        ),
    ]
