# Generated by Django 2.1.1 on 2019-04-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0036_auto_20190406_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_response',
            name='request',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='togther.Requests'),
            preserve_default=False,
        ),
    ]
