# Generated by Django 2.1.1 on 2019-04-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0037_form_response_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_response',
            old_name='request',
            new_name='request_id',
        ),
    ]
