# Generated by Django 2.1 on 2019-04-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0038_auto_20190407_1330'),
        ('togther', '0036_merge_20190330_1506'),
    ]

    operations = [
    ]
