# Generated by Django 2.1 on 2019-04-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togther', '0039_merge_20190407_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_response',
            name='request_id',
        ),
    ]
