from django.urls import path
from .view_chatroom_impl import (FetchChatroomView, CreateChatroomView, PinUnpinChatroomView, FetchAllChatroomView,
                                 LeaveSecretChatroomView, AddSecretChatroomParticipantView, GetTaggingList,
                                 AutoFollowChatroomForAllMembersView, EditChatroomView,
                                 FetchParticipantsOfSecretChatroom, CreateEventView, EventAddOrUpdateInstructor,
                                 EventAddOrUpdateHighlight, EventAddOrUpdateMemberTestimonial, EventAddOrUpdateFAQ,
                                 UpdateLastSeenEventChatroom,
                                 FetchUnseenCountInEvent, FetchLinkForEvent, FetchUserAllEvents, AttendEventView,
                                 UpdateEventView, SetEventAttendedView, EnableMemberMessageInChatroomView,
                                 FetchChatroomSettingsView, AddMembersToChatroomView,
                                 UpdateEventView, SetEventAttendedView, ChatroomUpdateFilesView,
                                 FetchAccessChatroomView, AddEventRecordingAttachment, FetchEventLinkForDashboard,
                                 AddEventRecordingAttachmentMeta, UpdateAccessWithOutSubscriptionView,
                                 DeleteEventRecordingAttachment, DeleteEventRecordingAttachmentMeta,
                                 RemoveCohortFromChatroomView, AddCohortToChatroomView, FetchChatroomParticipantsView,
                                 PublishEventWebflowView, FetchUserAllEventsMeta, ChangeChatroomTypeView,
                                 CreateDMChatroomView, BlockMemberView, RequestDMView, ScheduledChatroomFollow,
                                 ChatroomNotificationSettings, ChatroomParticipants, ChatroomInvites)

urlpatterns = [
    path('fetch', FetchChatroomView.as_view(), name="fetch_chatroom"),
    path('fetch_all', FetchAllChatroomView.as_view(), name="fetch_all_chatroom"),
    path('create', CreateChatroomView.as_view(), name="create_chatroom"),
    path('pin', PinUnpinChatroomView.as_view(), name="pin_unpin_chatroom"),
    path('secret/add', AddSecretChatroomParticipantView.as_view(), name="add_secret_room_participant"),
    path('secret/leave', LeaveSecretChatroomView.as_view(), name="leave_secret_chatroom"),
    path('get_tagging_list', GetTaggingList.as_view(), name="get_tagging_list"),
    path('auto_follow_for_all_members', AutoFollowChatroomForAllMembersView.as_view(),
         name="auto_follow_for_all_members"),
    path('edit', EditChatroomView.as_view(), name="edit_chatroom"),
    path('fetch_participants_meta', FetchChatroomParticipantsView.as_view(),
         name="fetch_participants_meta"),
    path('secret/fetch_participants_meta', FetchParticipantsOfSecretChatroom.as_view(),
         name="fetch_participants_of_secret_chatroom"),
    path('enable_member_message', EnableMemberMessageInChatroomView.as_view(),
         name='enable_member_message_in_chatroom'),
    path('fetch_settings', FetchChatroomSettingsView.as_view(),
         name='fetch_settings'),
    path('update_access', UpdateAccessWithOutSubscriptionView.as_view(), name='update_access'),
    path('fetch_access', FetchAccessChatroomView.as_view(), name='fetch_access'),
    path('change_type', ChangeChatroomTypeView.as_view(), name="change_type"),
    path('add', AddMembersToChatroomView.as_view(), name='add_members_to_chatroom'),
    path('remove_cohort', RemoveCohortFromChatroomView.as_view(), name="remove_cohort_from_chatroom"),
    path('add_cohorts', AddCohortToChatroomView.as_view(), name="add_cohorts_to_chatroom"),
    path('update_files', ChatroomUpdateFilesView.as_view(), name="update_files"),
    path('event/create', CreateEventView.as_view(), name="create_event"),
    path('event/add_or_update_instructor', EventAddOrUpdateInstructor.as_view(), name="add_or_update_instructor"),
    path('event/add_or_update_highlights', EventAddOrUpdateHighlight.as_view(), name="add_or_update_highlights"),
    path('event/add_or_update_member_testimonials', EventAddOrUpdateMemberTestimonial.as_view(),
         name="add_or_update_member_testimonials"),
    path('event/add_or_update_event_faq', EventAddOrUpdateFAQ.as_view(), name="add_or_update_event_faq"),
    path('event/update_last_seen', UpdateLastSeenEventChatroom.as_view(), name="update_last_seen"),
    path('event/fetch_unseen_count', FetchUnseenCountInEvent.as_view(), name="fetch_unseen_count_in_event"),
    path('event/fetch_link', FetchLinkForEvent.as_view(), name="fetch_link_for_event"),
    path('event/fetch_all', FetchUserAllEvents.as_view(), name="fetch_all_events"),
    path('event/fetch_all_meta', FetchUserAllEventsMeta.as_view(), name="fetch_all_events_meta"),
    path('event/attend', AttendEventView.as_view(), name="attend_event"),
    path('event/update', UpdateEventView.as_view(), name="update_event"),
    path('event/attended', SetEventAttendedView.as_view(), name="set_event_attended"),
    path('event/fetch_event_link_for_dashboard', FetchEventLinkForDashboard.as_view(),
         name="fetch_event_link_for_dashboard"),

    path('event/upload_recordings_meta', AddEventRecordingAttachmentMeta.as_view(), name='upload_recordings_meta'),
    path('event/upload_recordings', AddEventRecordingAttachment.as_view(), name='upload_recordings'),
    path('event/delete_recordings_meta', DeleteEventRecordingAttachmentMeta.as_view(), name='delete_recordings_meta'),
    path('event/delete_recordings', DeleteEventRecordingAttachment.as_view(), name='delete_recordings'),
    path('event/publish_webflow', PublishEventWebflowView.as_view(), name='publish_webflow'),
    path('create_dm', CreateDMChatroomView.as_view(), name='create_dm_chatroom'),
    path('block', BlockMemberView.as_view(), name='block_member'),
    path('request_dm', RequestDMView.as_view(), name='request_dm'),
    path('schedule_follow', ScheduledChatroomFollow.as_view(), name='schedule_follow'),
    path('notification_settings', ChatroomNotificationSettings.as_view(), name='notifications_settings'),
    path('participants', ChatroomParticipants.as_view(), name='chatroom_participants'),
    path('invites', ChatroomInvites.as_view(), name="chatroom_invites")
]
