Category_list = [ { "id" : 'al' , "title": 'Alumni'},
{ "id" : 'cl' , "title": 'College'},
{ "id" : 'sc' , "title": 'School'},
{ "id" : 'pf' , "title": 'Profession'},
{ "id" : 'nr' , "title": 'Native Roots'},
{ "id" : 'pa' , "title": 'Parenting'},
{ "id" : 'ev' , "title": 'Events'},
{ "id" : 'in' , "title":  'Interests'},
{ "id" : 'ed' , "title": 'Education'},
{ "id" : 'ac' , "title": 'Achievements'},
{ "id" : 'le' , "title": 'Learning'},
{ "id" : 'op' , "title": 'Opportunities'},
{ "id" : 'sp' , "title": 'Sports'},
{ "id" : 'ac' , "title": 'Activities'},
{ "id" : 'tr' , "title": 'Travel'},
{ "id" : 'ho' , "title": 'Hobbies'},
{ "id" : 're' , "title": 'Religious'},
{ "id" : 'po' , "title": 'Political'},
{ "id" : 'so' , "title": 'Social'},
{ "id" : 'mu' , "title": 'Music'},
{ "id" : 'be' , "title": 'Belief'},
{ "id" : 'fa' , "title": 'Fan'},
{ "id" : 'st' , "title": 'Startups'},
{ "id" : 'fi' , "title": 'Finance'},
{ "id" : 'in' , "title": 'Industry'},
{ "id" : 'sk' , "title": 'Skill'},
{ "id" : 'fa' , "title": 'Family'},
{ "id" : 'ca' , "title": 'Cause'},
{ "id" : 'ne' , "title": 'Neighborhood'},
{ "id" : 'hw' , "title": 'Health & Wellness'},
{ "id" : 'sf' , "title": 'Sports & Fitness'},
{ "id" : 'fd' , "title": 'Food & Drink'},
{ "id" : 'lc' , "title": 'Language & Culture'},
{ "id" : 'mo' , "title": 'Movement'},
{ "id" : 'ga' , "title": 'Games'},
{ "id" : 'ar' , "title": 'Art'},
{ "id" : 'fa' , "title": 'Fashion'},
{ "id" : 'br' , "title": 'Brand'},
]




