title = 'title'
Category_list = [ {title : 'Alumni'},
{title : 'College'},
{title : 'School'},
{title : 'Profession'},
{title : 'Native Roots'},
{title : 'Parenting'},
{title : 'Events'},
{title : 'Interests'},
{title : 'Education'},
{title : 'Achievements'},
{title : 'Learning'},
{title : 'Opportunities'},
{title : 'Sports'},
{title : 'Activities'},
{title : 'Travel'},
{title : 'Hobbies'},
{title : 'Religious'},
{title : 'Political'},
{title : 'Social'},
{title : 'Music'},
{title : 'Belief'},
{title : 'Fan'},
{title : 'Startups'},
{title : 'Finance'},
{title : 'Industry'},
{title : 'Skill'},
{title : 'Family'},
{title : 'Cause'},
{title : 'Neighborhood'},
{title : 'Health & Wellness'},
{title : 'Sports & Fitness'},
{title : 'Food & Drink'},
{title : 'Language & Culture'},
{title : 'Movement'},
{title : 'Games'},
{title : 'Art'},
{title : 'Fashion'},
{title : 'Brand'},
]




