Category_list = [ ('alumni' , 'Alumni'),
('college' , 'College'),
('school' , 'School'),
('profession' , 'Profession'),
('native roots' , 'Native Roots'),
('parenting' , 'Parenting'),
('events' , 'Events'),
('interests' , 'Interests'),
('education' , 'Education'),
('achievements' , 'Achievements'),
('learning' , 'Learning'),
('opportunities' , 'Opportunities'),
('sports' , 'Sports'),
('activities' , 'Activities'),
('travel' , 'Travel'),
('hobbies' , 'Hobbies'),
('religious' , 'Religious'),
('political' , 'Political'),
('social' , 'Social'),
('music' , 'Music'),
('belief' , 'Belief'),
('fan' , 'Fan'),
('startups' , 'Startups'),
('finance' , 'Finance'),
('industry' , 'Industry'),
('skill' , 'Skill'),
('family' , 'Family'),
('cause' , 'Cause'),
('neighborhood' , 'Neighborhood'),
('health & wellness' , 'Health & Wellness'),
('Sports & Fitness' , 'Sports & Fitness'),
('Food & Drink' , 'Food & Drink'),
('Language & Culture' , 'Language & Culture'),
('movement' , 'Movement'),
('games' , 'Games'),
('art' , 'Art'),
('fashion' , 'Fashion'),
('brand' , 'Brand'),
]




