from django.urls import path
from .views import *

urlpatterns = [
    path('', dashboard, name="admin_dashboard"),
    path('update_form/<int:community_id>', update_form, name='update_form'),
    path('community_delete/<int:community_id>',community_delete,name='community_delete'),
    path('add_dashboard_admin/<int:community_id>',add_dashboard_admin,name='add_dashboard_admin'),
    path('add_dashboard_member/<int:community_id>',add_dashboard_member,name='add_dashboard_member'),
    path('show_pending_member/<int:community_id>',show_pending_members,name='show_pending_member'),
    path('aprove_member/<int:community_id>/<int:member_id>',aprove_member,name='aprove_member'),
    path('decline_member/<int:community_id>/<int:member_id>', decline_member, name='decline_member'),
    path('show_tags/<int:community_id>', show_tags, name='show_tags'),
    path('add_tags',add_tags,name='add_tags'),
    path('update_user/<int:user_id>',update_user,name='update_user'),
    path('all_user',all_user,name='all_user'),
    path('send_invitation/<int:community_id>', send_invitation, name='send_invitation'),
    path('all_members/<int:community_id>', all_members, name='all_members'),
    path('delete_members/<int:community_id>/<int:member_id>', delete_members, name='delete_members'),

    path('add_questions/<int:community_id>', add_questions, name='add_questions'),
    path('delete_questions/<int:question_id>', delete_questions, name='delete_questions'),
    path('add_dropdown_responses/<int:question_id>', add_dropdown_responses, name='add_dropdown_responses'),

    path('analytics', analytics, name='analytics'),
    path('analytics_community/<int:community_id>', analytics_community, name='analytics_community'),
    path('deleted_communities', deleted_communities, name='deleted_communities'),
    path('update_user_tags/<int:user_id>', user_tags, name='update_user_tags'),
    path('add_user_tags',add_user_tags,name='add_user_tags'),
    path('hidden_tags/<int:community_id>', hidden_tags, name='hidden_tags'),
    path('add_hidden_tags', add_hidden_tags, name='add_hidden_tags'),
    path('alpha_sign_up_mail/<int:user_id>', alpha_sign_up_mail, name='alpha_sign_up_mail'),
    path('testing_sign_up_mail/<int:user_id>', testing_sign_up_mail, name='testing_sign_up_mail'),
    path('send_tester_mail', send_tester_mail, name='send_tester_mail'),
    path('user_communities/<int:user_id>', user_communities, name='user_communities'),
    path('add_community_tags/<int:community_id>', hidden_tags, name='add_community_tags'),
    path('create_tag',create_tag,name = 'create_tag'),
    path('categorize_tag',categorize_tag,name = 'categorize_tag'),
    path('delete_hidden_tags', delete_hidden_tags, name='delete_hidden_tags'),
    path('map_tags', map_tags, name='map_tags'),
    path('map_tags', map_tags, name='map_tags'),
    path('update_tag',update_tag,name = 'update_tag'),
    path('tag_update_form/<int:tag_id>', tag_update_form, name='tag_update_form'),
    path('delete_tags', delete_tags, name='delete_tags'),
    path('delete_tags_post/<int:tag_id>', delete_tags_post, name='delete_tags_post'),
    path('rename_tag', rename_tag, name='rename_tag'),
    path('rename_tag/<int:tag_id>', rename_tag, name='rename_tag_post'),
    path('get_tags/<int:attr_id>', get_tags_by_attributes, name='get_tags'),
    path('search', search, name='search'),
    path('metrics', metrics, name='metrics'),
    path('community_metrics', community_metrics, name='community_metrics'),
    path('community_metrics_filter', community_metrics_filter, name='community_metrics_filter'),
    path('hidden_tags_for_metrcis/<int:community_id>', hidden_tags_for_metrcis, name='hidden_tags_for_metrcis'),
    path('user_metrics', user_metrics, name='user_metrics'),
    path('getfile/<int:member_id>', getfile, name='getfile'),
    path('get_relevant_communities_file/<int:member_id>', get_relevant_communities_file, name='get_relevant_communities_file'),
    path('get_relevant_communities_link/<int:member_id>', get_relevant_communities_link,name='get_relevant_communities_link'),
    path('onboarding_metrics', onboarding_metrics, name='onboarding_metrics'),
    path('map_all_tags',map_all_tags,name='map_all_tags'),
    path('create_user_update', create_user_update, name='create_user_update'),
    path('disable_introduction_state/<int:community_id>', disable_introduction_state,name='disable_introduction_state'),
    path('enable_introduction_state/<int:community_id>', enable_introduction_state,name='enable_introduction_state'),

]
