from django.urls import path, include
from . import views
from collabmates_api import views as api_views
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('communities', api_views.communities, name="communities"),
    path('your_communities/<int:user_id>', api_views.your_communities, name="your_communities"),
    path('community/<int:community_id>', api_views.community, name="community"),
    path('similar_communities/<int:community_id>', api_views.similar_community, name="similar_community"),
    path('community/<int:community_id>/questions', api_views.join_community, name="join"),
    path('join_community', views.join_community_responses, name="join_community_responses"),
    path('categories', api_views.categories, name="categories"),
    path('create_community', api_views.create_community, name="create_community"),
    path('community/<str:category>', api_views.category_filter, name="category_filter"),
    path('user/<int:user_id>', api_views.user, name="user"),
    path('admins/<int:community_id>', api_views.admins, name="admins"),
    path('members/<int:community_id>', api_views.members, name="members"),
    path('create_collabcard', api_views.create_card, name="create_card"),
    path('collabcard/<int:card_id>', api_views.collabcard, name="collabcard"),
    path('community_collabcard/<int:community_id>', api_views.community_cards, name="community_cards"),
    path('create_answer', api_views.create_answer, name="create_answer"),
    path('login',api_views.login,name = 'login'),
    path('image_upload',api_views.image_upload,name = 'image'),
    path('add_admin/<int:community_id>',api_views.create_admin,name = 'create_admin'),
    path('pending_members/<int:community_id>',api_views.pending_members,name = 'pending_members'),
    path('join',api_views.request_response,name = 'join'),
    path('pending_members_count/<int:community_id>',api_views.pending_request_count,name = 'pending_request_count'),
    path('collabcard_seen', api_views.collabcards_seen, name='collabcard_seen'),
    path('members_state',api_views.members_state,name='members_state'),
    path('push', api_views.push, name='push'),
    path('collabcard_follow',api_views.collabcard_follow,name='collabcard_follow'),
    path('accept_invitation',views.accept_invitation,name='accept_invitation'),
    path('edit_community', views.edit_community, name='edit_community'),
    path('upload_attachment',api_views.upload_attachment,name='upload_attachment'),
    path('upload_files', api_views.upload_files, name='upload_files'),
    path('update_location',api_views.update_location,name='upload_location'),
    path('fetch_location/<int:user_id>',api_views.get_user_location,name='fetch_location'),
    path('decode_url', api_views.decode_url, name='decode_url'),
    path('all_members', api_views.all_members, name='all_members'),
    path('member_activity', api_views.member_activity, name='member_activity'),
    path('accept_promotership', api_views.accept_promotership, name='accept_promotership'),
    path('invite_members', api_views.invite_members, name='invite_members'),
    path('get_profile', api_views.get_profile, name='get_profile'),
    path('config', api_views.config, name='config'),
    path('onboarding', api_views.onboarding, name='onboarding'),
    path('push_onboarding', api_views.push_onboarding, name='push_onboarding'),

]
