MIXPANEL_NOTIFICATION_TRACKING_EVENT_NAME = "Notification Sent"
MIXPANEL_EVENT_MEMBER_APPROVED = "Member approved by cm"
MIXPANEL_EVENT_MEMBER_REJECTED = "Member rejected by cm"
MIXPANEL_EVENT_LEAVE_COMMUNITY = "Leave community"
