from django.urls import path
from collabmates_api.community.community_view_impl import (FetchCommunity, FetchChatroomFeed,
                                                           DeleteCommunityView, FetchCommunityFeedUrl,
                                                           FetchDiscoverableCommunities,
                                                           FetchCommunityOTLUrl, FetchMembersMeta,
                                                           FetchContentDownloadSettings, UpdateContentDownloadSettings,
                                                           FetchAllCommunities, FetchCommunityMeta, FetchCommunitySettings,
                                                           UpdateCommunitySettings, FetchCommunityToastsV1View,
                                                           UpdateCommunityToastV1View, JoinEmailAddView,
                                                           JoinEmailFetchView, FetchPaymentPageUrl,
                                                           CreateCommunityView, FetchGetStartedView,
                                                           SendInviteView, FetchCommunityFeedCM_OnboardingUrlView,
                                                           EditCommunityQuestionsView, FetchCommunityQuestionsView,
                                                           FetchCommunityBrandingView, FetchCommunityFromDomainView,
                                                           UpdateCommunityDMSettingsView, FetchCommunityDMSettingsView, 
                                                           FetchCommunityDMRightView, CommunityMemberView,
                                                           CommunityNotificationSettings,)

urlpatterns = [
    path('create', CreateCommunityView.as_view(), name="create_community"),
    path('fetch', FetchCommunity.as_view(), name="fetch_community"),
    path('fetch_all', FetchAllCommunities.as_view(), name="fetch_all_communities"),
    path('fetch_chatroom_feed', FetchChatroomFeed.as_view(), name="fetch_chatroom_feed"),
    path('delete',  DeleteCommunityView.as_view(), name="delete_community"),
    path('fetch_feed_url',  FetchCommunityFeedUrl.as_view(), name="fetch_feed_url"),
    path('fetch_feed_url_cm_onboarding', FetchCommunityFeedCM_OnboardingUrlView.as_view(),
         name="fetch_feed_url_cm_onboarding"),
    path('fetch_discoverable_communities', FetchDiscoverableCommunities.as_view(),
         name="fetch_discoverable_communities"),
    path('fetch_otl_url', FetchCommunityOTLUrl.as_view(), name="fetch_otl_url"),
    path('fetch_members_meta', FetchMembersMeta.as_view(), name="fetch_members"),
    path('fetch_content_download_settings', FetchContentDownloadSettings.as_view(), name="fetch_settings"),
    path('update_content_download_settings', UpdateContentDownloadSettings.as_view(), name="update_settings"),
    path('fetch_community_meta', FetchCommunityMeta.as_view(), name="fetch_community_meta"),

    path('fetch_community_settings', FetchCommunitySettings.as_view(), name="fetch_community_settings"),
    path('update_community_settings', UpdateCommunitySettings.as_view(), name="update_community_settings"),
    path('toast/fetch', FetchCommunityToastsV1View.as_view(), name="fetch_community_toasts"),
    path('toast/update', UpdateCommunityToastV1View.as_view(), name="update_community_toast"),
    path('join_email/add', JoinEmailAddView.as_view(), name="add_join_email"),
    path('join_email/fetch', JoinEmailFetchView.as_view(), name="fetch_join_email"),
    path('fetch_payment_page_url', FetchPaymentPageUrl.as_view(), name="fetch_payment_page_url"),
    path('fetch_get_started', FetchGetStartedView.as_view(), name="fetch_get_started"),
    path('invite', SendInviteView.as_view(), name="send_invite"),
    path('edit_questions', EditCommunityQuestionsView.as_view(), name="edit_questions"),
    path('questions', FetchCommunityQuestionsView.as_view(), name="fetch_community_questions"),
    path('<int:community_id>/branding', FetchCommunityBrandingView.as_view(), name="fetch_community_branding_info"),
    path('get_community_id', FetchCommunityFromDomainView.as_view(), name="fetch_community_from_domain"),
    path('update_community_dm_settings', UpdateCommunityDMSettingsView.as_view(), name="update_community_dm_settings"),
    path('fetch_community_dm_settings', FetchCommunityDMSettingsView.as_view(), name="fetch_community_dm_settings"),
    path('fetch_community_dm_right', FetchCommunityDMRightView.as_view(), name="fetch_community_dm_right"),
    path('member', CommunityMemberView.as_view(), name="community_member"),
    path('notification_settings', CommunityNotificationSettings.as_view(), name="community_notifications_settings")
]
