CHATROOM_FIELD_HEADER = "header"
CHATROOM_FIELD_TITLE = "title"
CHATROOM_FIELD_ID = "id"
CHATROOM_SEARCHABLE_FIELDS = [CHATROOM_FIELD_HEADER, CHATROOM_FIELD_TITLE, CHATROOM_FIELD_ID]

MEMBER_DIRECTORY_ORDER_BY_NAME = "alphabetical"
MEMBER_DIRECTORY_ORDER_BY_RECENT = "last_updated"
MEMBER_DIRECTORY_ORDER_BY_FIELDS = [MEMBER_DIRECTORY_ORDER_BY_NAME, MEMBER_DIRECTORY_ORDER_BY_RECENT]

MEMBER_DIRECTORY_FIELD_NAME = "name"
MEMBER_DIRECTORY_FIELD_TAG = "tag"
MEMBER_DIRECTORY_FIELD_COHORT_NAME = "cohort_name"
MEMBER_DIRECTORY_FIELD_USER_UNIQUE_ID = "user_unique_id"
MEMBER_DIRECTORY_FIELD_CLIENT_USER_UNIQUE_ID = "client_user_unique_id"

MEMBER_DIRECTORY_SEARCHABLE_FIELDS = [MEMBER_DIRECTORY_FIELD_NAME, MEMBER_DIRECTORY_FIELD_TAG,
                                      MEMBER_DIRECTORY_FIELD_COHORT_NAME, MEMBER_DIRECTORY_FIELD_USER_UNIQUE_ID, MEMBER_DIRECTORY_FIELD_CLIENT_USER_UNIQUE_ID]

MEMBER_DIRECTORY_INDEX_FIELDS_DICTIONARY_MAPPING = {
    MEMBER_DIRECTORY_FIELD_NAME: "member.user.name",
    MEMBER_DIRECTORY_FIELD_TAG: "custom_title",
    MEMBER_DIRECTORY_FIELD_COHORT_NAME: "cohorts.name",
    MEMBER_DIRECTORY_FIELD_USER_UNIQUE_ID:  "user_unique_id",
    MEMBER_DIRECTORY_FIELD_CLIENT_USER_UNIQUE_ID: "client_user_unique_id"
}

CUSTOM_INTRO_TEXT_FOR_ADMIN = "Created this community on %s"
CUSTOM_INTRO_TEXT_FOR_MEMBERS = "Joined via a private community link on %s"
CUSTOM_CLICK_TEXT_FOR_MEMBERS = "%s joined this community via a private community link on %s and hasn’t created " \
                                "their profile for this community yet"
